version: '2.1'

services:

  bloggerDB:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
    - /data/postgresql/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    
  blogger:
    image: blogger
    container_name: blogger
    ports:
    - 8081:8081
    depends_on:
    - bloggerDB
    environment:  
    - "SPRING_PROFILES_ACTIVE=development"